language: python

python: "3.6"

cache: pip

jobs:
  include:
    - stage: test
      install:
        - pip install -e .
      script: pytest --cov=./
      after_success: codecov

    - stage: deploy to pypi
      if: tag IS present
      script: skip
      deploy:
        - provider: pypi
          distributions: "sdist bdist_wheel"
          username: $PYPI_USERNAME
          password: $PYPI_PASSWORD
          on:
            tags: true
